db-uri = "postgres://bioapp:v7yTYdhwUObdPnsUoGt8W6NW5dy5rLlG@localhost:5432/biodinamicos"
db-schemas = "public"
db-anon-role = "anon"
server-port = 3001
jwt-secret = "60fbe00b1a938a795e143da6622ff24234275a2f2964d50f0ecda12cbe321a7f"
