-- Roles for PostgREST
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
END $$;

-- Grant bioapp (the POSTGRES_USER) ability to switch roles
GRANT anon TO bioapp;
GRANT authenticated TO bioapp;
 GRANT INSERT ON TABLE public.beta_feedback TO anon;
 GRANT TRIGGER ON TABLE public.beta_feedback TO anon;
 GRANT REFERENCES ON TABLE public.beta_feedback TO anon;
 GRANT TRUNCATE ON TABLE public.beta_feedback TO anon;
 GRANT DELETE ON TABLE public.beta_feedback TO anon;
 GRANT UPDATE ON TABLE public.beta_feedback TO anon;
 GRANT SELECT ON TABLE public.beta_feedback TO anon;
 GRANT TRIGGER ON TABLE public.biodynamic_preparations TO anon;
 GRANT INSERT ON TABLE public.biodynamic_preparations TO anon;
 GRANT SELECT ON TABLE public.biodynamic_preparations TO anon;
 GRANT UPDATE ON TABLE public.biodynamic_preparations TO anon;
 GRANT DELETE ON TABLE public.biodynamic_preparations TO anon;
 GRANT TRUNCATE ON TABLE public.biodynamic_preparations TO anon;
 GRANT REFERENCES ON TABLE public.biodynamic_preparations TO anon;
 GRANT INSERT ON TABLE public.farmer_contact_details TO anon;
 GRANT TRIGGER ON TABLE public.farmer_contact_details TO anon;
 GRANT REFERENCES ON TABLE public.farmer_contact_details TO anon;
 GRANT TRUNCATE ON TABLE public.farmer_contact_details TO anon;
 GRANT DELETE ON TABLE public.farmer_contact_details TO anon;
 GRANT UPDATE ON TABLE public.farmer_contact_details TO anon;
 GRANT SELECT ON TABLE public.farmer_contact_details TO anon;
 GRANT SELECT ON TABLE public.farmer_profiles TO anon;
 GRANT TRIGGER ON TABLE public.farmer_profiles TO anon;
 GRANT REFERENCES ON TABLE public.farmer_profiles TO anon;
 GRANT TRUNCATE ON TABLE public.farmer_profiles TO anon;
 GRANT DELETE ON TABLE public.farmer_profiles TO anon;
 GRANT UPDATE ON TABLE public.farmer_profiles TO anon;
 GRANT INSERT ON TABLE public.farmer_profiles TO anon;
 GRANT INSERT ON TABLE public.farmer_profiles_public TO anon;
 GRANT SELECT ON TABLE public.farmer_profiles_public TO anon;
 GRANT UPDATE ON TABLE public.farmer_profiles_public TO anon;
 GRANT DELETE ON TABLE public.farmer_profiles_public TO anon;
 GRANT TRUNCATE ON TABLE public.farmer_profiles_public TO anon;
 GRANT REFERENCES ON TABLE public.farmer_profiles_public TO anon;
 GRANT TRIGGER ON TABLE public.farmer_profiles_public TO anon;
 GRANT TRIGGER ON TABLE public.messages TO anon;
 GRANT SELECT ON TABLE public.messages TO anon;
 GRANT UPDATE ON TABLE public.messages TO anon;
 GRANT DELETE ON TABLE public.messages TO anon;
 GRANT TRUNCATE ON TABLE public.messages TO anon;
 GRANT REFERENCES ON TABLE public.messages TO anon;
 GRANT INSERT ON TABLE public.messages TO anon;
 GRANT TRIGGER ON TABLE public.product_variations TO anon;
 GRANT INSERT ON TABLE public.product_variations TO anon;
 GRANT SELECT ON TABLE public.product_variations TO anon;
 GRANT UPDATE ON TABLE public.product_variations TO anon;
 GRANT DELETE ON TABLE public.product_variations TO anon;
 GRANT TRUNCATE ON TABLE public.product_variations TO anon;
 GRANT REFERENCES ON TABLE public.product_variations TO anon;
 GRANT INSERT ON TABLE public.products TO anon;
 GRANT TRIGGER ON TABLE public.products TO anon;
 GRANT REFERENCES ON TABLE public.products TO anon;
 GRANT TRUNCATE ON TABLE public.products TO anon;
 GRANT DELETE ON TABLE public.products TO anon;
 GRANT UPDATE ON TABLE public.products TO anon;
 GRANT SELECT ON TABLE public.products TO anon;
 GRANT SELECT ON TABLE public.user_preferences TO anon;
 GRANT INSERT ON TABLE public.user_preferences TO anon;
 GRANT TRIGGER ON TABLE public.user_preferences TO anon;
 GRANT REFERENCES ON TABLE public.user_preferences TO anon;
 GRANT TRUNCATE ON TABLE public.user_preferences TO anon;
 GRANT DELETE ON TABLE public.user_preferences TO anon;
 GRANT UPDATE ON TABLE public.user_preferences TO anon;
 GRANT SELECT ON TABLE public.user_roles TO anon;
 GRANT TRIGGER ON TABLE public.user_roles TO anon;
 GRANT REFERENCES ON TABLE public.user_roles TO anon;
 GRANT TRUNCATE ON TABLE public.user_roles TO anon;
 GRANT DELETE ON TABLE public.user_roles TO anon;
 GRANT UPDATE ON TABLE public.user_roles TO anon;
 GRANT INSERT ON TABLE public.user_roles TO anon;
 GRANT TRUNCATE ON TABLE public.users TO anon;
 GRANT TRIGGER ON TABLE public.users TO anon;
 GRANT REFERENCES ON TABLE public.users TO anon;
 GRANT DELETE ON TABLE public.users TO anon;
 GRANT UPDATE ON TABLE public.users TO anon;
 GRANT SELECT ON TABLE public.users TO anon;
 GRANT INSERT ON TABLE public.users TO anon;
 GRANT INSERT ON TABLE public.biodynamic_preparations TO authenticated;
 GRANT TRIGGER ON TABLE public.biodynamic_preparations TO authenticated;
 GRANT REFERENCES ON TABLE public.biodynamic_preparations TO authenticated;
 GRANT TRUNCATE ON TABLE public.biodynamic_preparations TO authenticated;
 GRANT DELETE ON TABLE public.biodynamic_preparations TO authenticated;
 GRANT UPDATE ON TABLE public.biodynamic_preparations TO authenticated;
 GRANT SELECT ON TABLE public.biodynamic_preparations TO authenticated;
 GRANT SELECT ON TABLE public.farmer_contact_details TO authenticated;
 GRANT INSERT ON TABLE public.farmer_contact_details TO authenticated;
 GRANT TRIGGER ON TABLE public.farmer_contact_details TO authenticated;
 GRANT REFERENCES ON TABLE public.farmer_contact_details TO authenticated;
 GRANT TRUNCATE ON TABLE public.farmer_contact_details TO authenticated;
 GRANT DELETE ON TABLE public.farmer_contact_details TO authenticated;
 GRANT UPDATE ON TABLE public.farmer_contact_details TO authenticated;
 GRANT UPDATE ON TABLE public.farmer_profiles TO authenticated;
 GRANT SELECT ON TABLE public.farmer_profiles TO authenticated;
 GRANT TRIGGER ON TABLE public.farmer_profiles TO authenticated;
 GRANT REFERENCES ON TABLE public.farmer_profiles TO authenticated;
 GRANT INSERT ON TABLE public.farmer_profiles TO authenticated;
 GRANT TRUNCATE ON TABLE public.farmer_profiles TO authenticated;
 GRANT DELETE ON TABLE public.farmer_profiles TO authenticated;
 GRANT UPDATE ON TABLE public.farmer_profiles_public TO authenticated;
 GRANT INSERT ON TABLE public.farmer_profiles_public TO authenticated;
 GRANT SELECT ON TABLE public.farmer_profiles_public TO authenticated;
 GRANT DELETE ON TABLE public.farmer_profiles_public TO authenticated;
 GRANT TRUNCATE ON TABLE public.farmer_profiles_public TO authenticated;
 GRANT REFERENCES ON TABLE public.farmer_profiles_public TO authenticated;
 GRANT TRIGGER ON TABLE public.farmer_profiles_public TO authenticated;
 GRANT REFERENCES ON TABLE public.messages TO authenticated;
 GRANT INSERT ON TABLE public.messages TO authenticated;
 GRANT SELECT ON TABLE public.messages TO authenticated;
 GRANT UPDATE ON TABLE public.messages TO authenticated;
 GRANT DELETE ON TABLE public.messages TO authenticated;
 GRANT TRUNCATE ON TABLE public.messages TO authenticated;
 GRANT TRIGGER ON TABLE public.messages TO authenticated;
 GRANT INSERT ON TABLE public.product_variations TO authenticated;
 GRANT TRIGGER ON TABLE public.product_variations TO authenticated;
 GRANT REFERENCES ON TABLE public.product_variations TO authenticated;
 GRANT TRUNCATE ON TABLE public.product_variations TO authenticated;
 GRANT DELETE ON TABLE public.product_variations TO authenticated;
 GRANT UPDATE ON TABLE public.product_variations TO authenticated;
 GRANT SELECT ON TABLE public.product_variations TO authenticated;
 GRANT REFERENCES ON TABLE public.products TO authenticated;
 GRANT SELECT ON TABLE public.products TO authenticated;
 GRANT UPDATE ON TABLE public.products TO authenticated;
 GRANT DELETE ON TABLE public.products TO authenticated;
 GRANT TRUNCATE ON TABLE public.products TO authenticated;
 GRANT TRIGGER ON TABLE public.products TO authenticated;
 GRANT INSERT ON TABLE public.products TO authenticated;
 GRANT INSERT ON TABLE public.user_preferences TO authenticated;
 GRANT TRIGGER ON TABLE public.user_preferences TO authenticated;
 GRANT SELECT ON TABLE public.user_preferences TO authenticated;
 GRANT DELETE ON TABLE public.user_preferences TO authenticated;
 GRANT TRUNCATE ON TABLE public.user_preferences TO authenticated;
 GRANT UPDATE ON TABLE public.user_preferences TO authenticated;
 GRANT REFERENCES ON TABLE public.user_preferences TO authenticated;
 GRANT REFERENCES ON TABLE public.user_roles TO authenticated;
 GRANT TRIGGER ON TABLE public.user_roles TO authenticated;
 GRANT INSERT ON TABLE public.user_roles TO authenticated;
 GRANT SELECT ON TABLE public.user_roles TO authenticated;
 GRANT UPDATE ON TABLE public.user_roles TO authenticated;
 GRANT DELETE ON TABLE public.user_roles TO authenticated;
 GRANT TRUNCATE ON TABLE public.user_roles TO authenticated;
 GRANT TRIGGER ON TABLE public.users TO authenticated;
 GRANT INSERT ON TABLE public.users TO authenticated;
 GRANT REFERENCES ON TABLE public.users TO authenticated;
 GRANT TRUNCATE ON TABLE public.users TO authenticated;
 GRANT DELETE ON TABLE public.users TO authenticated;
 GRANT UPDATE ON TABLE public.users TO authenticated;
 GRANT SELECT ON TABLE public.users TO authenticated;

 GRANT USAGE, SELECT ON SEQUENCE public.beta_feedback_id_seq TO anon;

 GRANT USAGE, SELECT ON SEQUENCE public.beta_feedback_id_seq TO authenticated;

